### ISSUE TITLE
Question about lat lng

### ISSUE THREAD

**Issue by iannsp** [kamranahmedse/php-geocode#9]
Why did u request 2 times for data?
one with address itself and another with latlng data.

**Comment by kamranahmedse** [comment]
Hey @iannsp,

I guess I should have documented that. Anyways, I wrote this script way back in time and I can't remember the exact reason. But I guess it was because of the reason that the first time i.e. when using the address, I wasn't getting the proper results i.e. with all the details that I wanted but when I used the latitude longitude, I was getting the required details so I had to first convert the address to lat, lng and then use that info to get the required details.

Thank you.

**Comment by iannsp** [comment]
understood.
I saw your docblocks and it say something about this but it is not necessary. I check both requests and you have the data in your first request.
When you do this two requests and use some data from  latLng request with the Full-Addressed request you create a problem: Google can answers different data for latLng request you get from a Full-Address request.

**Comment by kamranahmedse** [comment]
Thank you for pointing it out. I will look into it.
